# Generated by Django 3.0.4 on 2021-11-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'コメント'},
        ),
        migrations.AlterModelOptions(
            name='threads',
            options={'verbose_name_plural': 'スレッド'},
        ),
    ]
