# Generated by Django 3.0.4 on 2021-11-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0003_auto_20211106_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
