# Generated by Django 3.0.4 on 2021-11-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0005_auto_20211108_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='first_body',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='threads',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
